# Generated by Django 3.1.2 on 2020-10-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, help_text='If null then game object was automatically generated.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_objects', to='room.player')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.location')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_objects', to='world.world')),
            ],
        ),
    ]
